version: '3.8'

services:

  backend:
    build:
      context: ./apps/backend
      dockerfile: Dockerfile
    container_name: reomco-backend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://neondb_owner:npg_ojeZnCJc02Bk@ep-long-tree-atppuuu0.c-9.us-east-1.aws.neon.tech/neondb?sslmode=require
      - JWT_SECRET=supersecretkey_dev
    networks:
      - reomco-network

  frontend:
    build:
      context: ./apps/frontend
      dockerfile: Dockerfile
    container_name: reomco-frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - reomco-network

networks:
  reomco-network:
    driver: bridge


