version: '3.8'

services:

  backend:
    build:
      context: ./apps/backend
      dockerfile: Dockerfile
    container_name: reomco-backend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=mysql://admin:12345678@retailedge-db.cluster-crausyiq2p70.ap-south-1.rds.amazonaws.com:3306/retailedge
      - JWT_SECRET=supersecretkey_dev
    networks:
      - reomco-network

  frontend:
    build:
      context: ./apps/frontend
      dockerfile: Dockerfile
    container_name: reomco-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - reomco-network

networks:
  reomco-network:
    driver: bridge


